coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto 
        threshold: 5
        if_ci_failed: error
        only_pulls: true

comment: 
  layout: " diff, flags, files"
  behavior: default
  require_changes: false 
  require_base: false  
  require_head: true  
  hide_project_coverage: false
